FROM ubuntu:22.04
WORKDIR /app
RUN apt update; apt install libgl1-mesa-glx libglib2.0-0 python3 python3-venv -y
RUN python3 -m venv venv
RUN venv/bin/pip install matplotlib
RUN venv/bin/pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
COPY . .
CMD ["bash"]